import {StyleSheet} from 'react-native';
import {hp, wp} from '../../util';

const createStyles = theme => {
  const styles = StyleSheet.create({
    mainContainer: {
      flex: 1,
      backgroundColor: theme.color.textWhite,
    },
    subContainer: {
      height: hp(12),
      backgroundColor: theme.color.headerBackgroundColor,
      borderBottomLeftRadius: hp(5),
      borderBottomRightRadius: hp(5),
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingLeft: hp(2),
      alignItems: 'center',
      paddingBottom: hp(2),
    },
    headerInitialText: {
      fontSize: hp(3),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.boldFamily,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignContent: 'center',
    },
    headerLastText: {
      fontSize: theme.size.xLarge,
      color: theme.color.backgroundColor,
      textAlign: 'center',
    },
    headerContainerStyle: {
      borderBottomColor: theme.color.headerBackgroundColor,
    },
    headerColor: theme.color.headerBackgroundColor,
    addMemoryIcon: theme.color.backgroundColor,
    container: {
      flexGrow: 1,
      paddingHorizontal: wp(8),
      paddingVertical: hp(3),
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    homeText: {
      fontSize: theme.size.large,
    },
    newMemoryButton: {
      alignSelf: 'center',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      // padding: hp(2.75),
      width: wp(65),
      height: hp(7),
      borderRadius: hp(5),
      borderWidth: hp(0.1),
      borderColor: theme.color.headerBackgroundColor,
    },
    modalButtonText: {
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.boldFamily,
    },
    becomeMemberButton: {
      alignSelf: 'center',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      // padding: hp(2.5),
      width: wp(60),
      height: hp(6.5),
      borderRadius: hp(5),
      borderWidth: hp(0.1),
      borderColor: theme.color.backgroundColor,
      // backgroundColor: theme.color.backgroundColor,
      backgroundColor: theme.color.backgroundColor,
      marginVertical: hp(2),
    },
    becomeMmeberText: {
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.boldFamily,
      color: theme.color.textWhite,
      textAlign: 'center',
    },
    textFieldTile: {
      marginVertical: hp(4),
      fontSize: theme.size.medium,
      textAlign: 'center',
      fontFamily: theme.fontFamily.boldFamily,
    },
    bottomText: {
      fontSize: theme.size.medium,
      textAlign: 'center',
      fontFamily: theme.fontFamily.boldFamily,
    },
    modalTitle: {
      marginTop: -hp(3),
      fontSize: theme.size.medium,
      textAlign: 'center',
      fontFamily: theme.fontFamily.boldFamily,
    },
    fieldText: {
      fontSize: theme.size.medium,
      textAlign: 'center',
      fontFamily: theme.fontFamily.mediumFamily,
    },
    donationText: {
      marginVertical: hp(4),
      fontSize: theme.size.medium,
      textAlign: 'center',
      fontFamily: theme.fontFamily.mediumFamily,
    },
    benefitText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.mediumFamily,
    },
    benefitDetailText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.mediumFamily,
      marginLeft: wp(4),
    },
    bottomView: {
      marginTop: hp(6),
    },
    avatarImage: {marginRight: wp(5)},
    profileImage: {
      marginRight: wp(5),
      marginBottom: hp(3),
    },
    firstMemoryText: {
      fontSize: theme.size.medium,
      paddingBottom: hp(2),
    },
    dialogStyle: {
      backgroundColor: 'white',
      height: hp(45),
      width: wp(75),
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
    },
    contentStyle: {
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'column',
      justifyContent: 'center',
    },
    modalButton: {
      alignSelf: 'center',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      width: hp(32),
      height: hp(7),
      borderRadius: hp(5),
      borderWidth: hp(0.1),
      borderColor: theme.color.headerBackgroundColor,
      marginBottom: hp(2),
    },
    secondaryButton: {
      alignSelf: 'center',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      width: hp(32),
      height: hp(7),
      borderRadius: hp(5),
      borderWidth: hp(0.1),
      borderWidth: hp(0.1),
      borderColor: theme.color.backgroundColor,
      backgroundColor: theme.color.backgroundColor,
      marginBottom: hp(2),
    },
    secondaryButtonText: {
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.boldFamily,
      color: theme.color.textWhite,
    },
    newMmemoryButtonText: {
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.boldFamily,
    },
    modalCloseIcon: {justifyContent: 'flex-end', alignSelf: 'flex-end'},
    iconHeaderContainer: {width: '10%', paddingLeft: hp(1)},
    headerTitleContainer: {
      flexDirection: 'row',
      width: '75%',
      alignSelf: 'center',
      justifyContent: 'center',
      alignContent: 'center',
    },
    memberView: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: hp(2),
    },
    privacyText: {
      color: theme.color.textPurple,
      textDecorationLine: 'underline',
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.mediumFamily,
    },
    andText: {
      marginHorizontal: wp(1),
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.mediumFamily,
    },
    restoreText: {
      color: theme.color.textPurple,
      textDecorationLine: 'underline',
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.boldFamily,
      marginBottom: hp(2),
    },
    subscriptionHeader: {
      color: theme.color.textPurple,
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.boldFamily,
      marginTop: hp(2),
    },
    subscriptionText: {
      textAlign: 'center',
      fontSize: theme.size.small,
    },
    monthText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.boldFamily,
    },
    perText: {
      marginHorizontal: wp(2),
    },
    privacyView: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    modalStyle: {
      backgroundColor: 'white',
      alignSelf: 'center',
    },
    rowContainer: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      marginBottom: hp(3),
    },
    modalHeader: {
      flex: 1,
      fontSize: hp(2.7),
      textAlign: 'center',
      fontFamily: theme.fontFamily.boldFamily,
    },
    modalCloseIcon: {
      justifyContent: 'flex-end',
      alignSelf: 'flex-end',
    },
    modalText: {
      fontSize: hp(2.2),
      alignSelf: 'center',
      // textAlign: 'center',
      fontFamily: theme.fontFamily.mediumFamily,
      width: wp(60),
      marginBottom: hp(1),
    },
  });
  return styles;
};
export default createStyles;
